<?php
/**
 * @file
 * Trouble Ticket Module for Drupal 7.x
 *
 * This module displays a form for submitting trouble tickets and,
 * when submitted, creates a corresponding ticket in FogBugz and
 * sends the user a confirmation email.
 */

/**
 * Implements hook_menu().
 */
function trouble_tickets_menu() {
  $items = array();
  $items['trouble-tickets'] = array(
    'title' => 'Trouble Tickets',
    'description' => 'Form for submitting trouble tickets',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('trouble_tickets_form'),
    'access arguments' => array('access trouble_tickets'),
    'file' => 'trouble_tickets_form.inc',
    'file path' => drupal_get_path('module', 'trouble_tickets') . '/forms',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function trouble_tickets_permission() {
  return array(
    'access trouble_tickets' => array(
      'title' => t('Access content for the Trouble Tickets module'),
    )
  );
}

/**
 * Implements hook_help().
 */
function trouble_tickets_help($path, $arg) {
  switch ($path) {
    case "admin/help#trouble_tickets":
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Trouble Tickets module displays a ticket submission form and pushes submitted tickets to FogBugz. Remember to include the FogBugz credentials in the module configuration settings, and to set the module permissions.') . '</p>';
      return $output;
  }
}

/**
 * Returns appropriate ticket priority based on category.
 *
 * @param string $category
 *   Category of ticket
 *
 * @return int
 *   Priority of ticket
 */
function _trouble_tickets_get_priority($category) {
  switch ($category) {
    case 'Bug':
      return 2;

    break;

    case 'Inquiry':
      return 3;

    break;

    case 'New Feature':
      return 4;

    break;
  }
}
